### ISSUE TITLE
Sound card list is empty 

### ISSUE THREAD

**Issue by zmata** [christianTF/LoxBerry-Plugin-squeezelite#53]
Sound devices list is empty in Zones configuration in DEV version.
In 0.5.1 everything is OK.

**Comment by christianTF** [comment]
Nothing changed with that version.

Usually, a reboot would help, as permissions are set during first startup after a plugin install/update.

**Comment by zmata** [comment]
Reboot was done. 
I uninstal it and install 0.5.1 + reboot - everything OK.
I Install back dev + reboot - List is empty.
Also I tried to uninstall first + reboot before install dev.

**Comment by christianTF** [comment]
Nothing changed (only language specific things we I've changed the last days): https://github.com/christianTF/LoxBerry-Plugin-squeezelite/compare/0.5.1...dev

Please be careful when uninstalling and installing (not updating) the plugin.
- If you uninstall it, it will _delete_ permissions on next boot.
- If you install, it will _set_ permissions on next boot.

If you uninstall and install it without reboots, it presumably will delete permissions from the uninstall task on next boot, that should have been set by the install task.

Therefore, 
- only update (and reboot), or
- uninstall, reboot, install, reboot

If you change the binary in the UI, you also need to reboot.

This reboot orgy only can be fixed by switching to the Plugin-Interface V2, loosing compatibility for LoxBerry 0.2.x.

**Comment by zmata** [comment]
Problem was on my side. 
I'm sorry!
You can close issue.
